disabled = false
languageCode = "zh-tw"
languageName = "中文"
weight = 1
title = "Shen-Chih Hsu"

[params]
  displayName = "中文"
  isoCode = "zh-tw"
  rtl = false
  dateFormat = "2006.01.02"
  # logo = "main.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Shen-Chih Hsu 徐珅鋕，紀錄筆記"
  copyright = "@2025 Shen-Chih Hsu 徐珅鋕"

[params.author]
   name = "Shen-Chih Hsu"
#   email = "youremail@example.com"
#   image = "img/blowfish_logo.png"
#   imageQuality = 96
#   headline = "I'm only human"
#    bio = "A little bit about you"
   links = [
     { substack = "https://shenchihhsu.substack.com/" },
     { link = "https://shenchihhsu.com/" }
   ]
